# Generated by Django 3.0.6 on 2020-05-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0002_auto_20200519_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SelfIntroduce',
        ),
    ]
