# Generated by Django 3.0.6 on 2020-05-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0003_remove_profile_selfintroduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='myuser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myuser',
        ),
    ]
