# Generated by Django 3.0.6 on 2020-05-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0006_auto_20200520_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
    ]
