# Generated by Django 3.0.6 on 2020-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0007_remove_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.IntegerField(),
        ),
    ]
