# Generated by Django 3.0.6 on 2020-05-20 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0008_auto_20200521_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='date',
        ),
    ]
