# Generated by Django 3.0.6 on 2020-05-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diplom', '0009_auto_20200521_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
