# Generated by Django 3.0.6 on 2020-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0011_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='audio'),
        ),
    ]
