# Generated by Django 3.0.6 on 2020-05-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0012_auto_20200521_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
