# Generated by Django 3.0.6 on 2020-05-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0013_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom.Data'),
        ),
    ]
