# Generated by Django 3.0.6 on 2020-05-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0014_auto_20200522_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
