# Generated by Django 3.0.6 on 2020-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0016_auto_20200523_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
