# Generated by Django 3.0.6 on 2020-05-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diplom', '0017_auto_20200523_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
